<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-10-19T02:14:02 IST" name="Suite" finished-at="2023-10-19T02:14:42 IST" duration-ms="40298">
    <groups>
    </groups>
    <test started-at="2023-10-19T02:14:02 IST" name="Project" finished-at="2023-10-19T02:14:39 IST" duration-ms="37250">
      <class name="Pom.Project">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Pom.Project@1622f1b]" started-at="2023-10-19T02:14:02 IST" name="launchApplication" finished-at="2023-10-19T02:14:05 IST" duration-ms="3185" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder()[pri:0, instance:Pom.Project@1622f1b]" started-at="2023-10-19T02:14:05 IST" name="submitOrder" finished-at="2023-10-19T02:14:26 IST" duration-ms="20866" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Pom.Project@1622f1b]" started-at="2023-10-19T02:14:26 IST" name="tearDown" finished-at="2023-10-19T02:14:26 IST" duration-ms="142" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Pom.Project@1622f1b]" started-at="2023-10-19T02:14:26 IST" name="launchApplication" finished-at="2023-10-19T02:14:29 IST" duration-ms="2774" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="validateOrderHistoryPage()[pri:0, instance:Pom.Project@1622f1b]" started-at="2023-10-19T02:14:29 IST" name="validateOrderHistoryPage" finished-at="2023-10-19T02:14:39 IST" depends-on-methods="Pom.Project.submitOrder" duration-ms="10132" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [null] but found [adidas original]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [null] but found [adidas original]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Pom.Project.validateOrderHistoryPage(Project.java:153)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateOrderHistoryPage -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Pom.Project@1622f1b]" started-at="2023-10-19T02:14:39 IST" name="tearDown" finished-at="2023-10-19T02:14:39 IST" duration-ms="114" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Pom.Project -->
    </test> <!-- Project -->
    <test started-at="2023-10-19T02:14:39 IST" name="ErrorValidation" finished-at="2023-10-19T02:14:42 IST" duration-ms="3020">
      <class name="Pom.ErrorValidation">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Pom.ErrorValidation@6c80d78a]" started-at="2023-10-19T02:14:39 IST" name="launchApplication" finished-at="2023-10-19T02:14:41 IST" duration-ms="2040" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder()[pri:0, instance:Pom.ErrorValidation@6c80d78a]" started-at="2023-10-19T02:14:41 IST" name="submitOrder" finished-at="2023-10-19T02:14:42 IST" duration-ms="855" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Pom.ErrorValidation@6c80d78a]" started-at="2023-10-19T02:14:42 IST" name="tearDown" finished-at="2023-10-19T02:14:42 IST" duration-ms="122" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Pom.ErrorValidation -->
    </test> <!-- ErrorValidation -->
  </suite> <!-- Suite -->
</testng-results>
